<?php
/**
 * @file
 * Adds an image title to the tooltip and displays it on the slider.
 */

/**
 * Implements function hook_views_pre_render().
 *
 * This function is used for rendering the image title, so that a tooltip can display the
 * title on the slider carousel.
 *
 * @param $view The view object about to be processed.
 */
function slider_tooltip_views_pre_render(&$view) {

    if ($view->name === 'wissenskarten' && isset($view->style_options['id'])) {
        if ($view->style_options['id'] === 'carousel_wk') {

            /* Iterates over all thumbnail images. */
            foreach($view->result as $image) {

                $image_title = $image->node_title;
                $image->field_field_wk_bild[0]['rendered']['#item']['title'] = $image_title;
                $image->field_field_wk_bild[0]['rendered']['#item']['field_file_image_title_text'] = $image_title;
            }
        }
    }
}

/**
 * Implements hook_help().
 * Display help link to README.txt in module overview (admin/modules).
 */
function slider_tooltip_help($path, $arg) {
  switch ($path) {
    case 'admin/help#slider_tooltip':
      $readme = file_get_contents(drupal_get_path('module', 'slider_tooltip') . '/README.txt');
      return module_exists('markdown') ? filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $readme)) : '<pre>' . check_plain($readme) . '</pre>';
  }
}