<?php

function slider_tooltip_views_pre_render(&$view) {
    if ($view->name === 'wissenskarten') {
        if ($view->style_options['id'] === 'carousel_wk') {

            foreach($view->result as $image) {
                $image_title = $image->node_title;
                $image->field_field_wk_bild[0]['rendered']['#item']['title'] = $image_title;
                $image->field_field_wk_bild[0]['rendered']['#item']['field_file_image_title_text'] = $image_title;
            }
        }
    }
}
