<?php

/**
 * Implements Hook_user_view_alter.
 *
 * @param $build
 */
function user_profile_elements_overview_user_view_alter(&$build) {
    $build['elementsoverviewhtml'] = array(
        '#markup' => elements_overview_html(array('biblio', 'wissenskarte', 'projekt', 'analysereport', 'forschungsergebnis')),
        '#weight' => '6',
        '#attached' => array('css' => array(drupal_get_path('module', 'user_profile_elements_overview') . "/css/user_profile_elements_overview.css"))
    );
}

function elements_overview_html($staticFilter = []) {
    global $user;
    $uid = $user->uid;
    $html = "";

    $query = "SELECT nid, type, title FROM {node}
            WHERE uid = :uid and type in (:staticFilter);";
    $results = db_query($query, array(":uid" => $uid, ":staticFilter" => $staticFilter));
    $results = $results->fetchAll();

    $html .= "<h3>Selbst angelegte Elemente</h3>";
    $html .= "<ol class='elementsoverview' style='list-style-type:none;'>";

    /*
     * Display different icons for various content types of created elements.
     */
    foreach($results as $result) {
        //dummy icons
        $html .= "<li>";
        switch($result->type) {
            case "biblio":
                $html .= "<i class='fa fa-file-text-o pub' aria-hidden='true'></i>";
                break;
            case "wissenskarte":
                $html .= "<i class='fa fa-file-word-o wk' aria-hidden='true'></i>";
                break;
            case "projekt":
                $html .= "<i class='fa fa-file-o projekt' aria-hidden='true'></i>";
                break;
            case "analysereport":
                $html .= "<i class='fa fa-file-pdf-o areport' aria-hidden='true'></i>";
                break;
            case "forschungsergebnis":
                $html .= "<i class='fa fa-files-o fergebnis' aria-hidden='true'></i>";
                break;
            default:
                $html .= "<i class='fa fa-file default' aria-hidden='true'></i>";
        }
        /* Links to the View of the created element. */
        $url = url('node/'. $result->nid);
        $html .= "<a href='$url'>$result->title</a>";
        //$html .= l($result->title, $url . '/edit', array('query' => drupal_get_destination()));
        $html .= "</li>";
    }

    $html .= "</ol>";

    return $html;
}