<?php
function form_wissenskarte_module_preprocess_page(&$vars)
{
  if (isset($vars['node']) && $vars['node']->type == 'wissenskarte') {
    drupal_add_js(drupal_get_path('module', 'form_wissenskarte_module') . "/js/morphmapping.js", array('scope' => 'footer', 'weight' => 5));
    drupal_add_js(drupal_get_path('module', 'form_wissenskarte_module') . "/js/morphmapping_edit.view.js", array('scope' => 'footer', 'weight' => 6));

    drupal_add_css(drupal_get_path('module', 'form_wissenskarte_module') . "/css/morphmapping.css");
    drupal_add_js(drupal_get_path('module', 'form_wissenskarte_module') . "/js/jquery.qtip.min.js");
    drupal_add_css(drupal_get_path('module', 'form_wissenskarte_module') . "/css/jquery.qtip.css");
  }
}

function form_wissenskarte_module_field_widget_image_image_form_alter(&$element, &$form_state, $context)
{
  // load only for type = "wissenskarte"
  $pathAddWissenskarte = 'node/add/wissenskarte';
  $isPathAddWissenskarte = drupal_match_path(current_path(), $pathAddWissenskarte);

  if ($isPathAddWissenskarte) {
    drupal_add_js(drupal_get_path('module', 'form_wissenskarte_module') . "/js/morphmapping.js", array('scope' => 'footer', 'weight' => 5));
    drupal_add_js(drupal_get_path('module', 'form_wissenskarte_module') . "/js/morphmapping_add.js", array('scope' => 'footer', 'weight' => 5));

    drupal_add_css(drupal_get_path('module', 'form_wissenskarte_module') . "/css/morphmapping.css");
  }
}

