<?php
/**
 * Implements hook_apachesolr_search_page_alter().
 * Adds a link to the search results page to export the search results as a csv file.
 *
 * @param array $build
 * @param array $search_page
 */
function morphsearch_csv_export_apachesolr_search_page_alter(array &$build, array $search_page) {
  $env_id = $search_page['env_id'];
  if (apachesolr_has_searched($env_id)) {
    // get the Solr query and extract the portion the user entered through the search block
    $solrQuery  = apachesolr_current_query($env_id);

    if ($solrQuery) {
      $response = apachesolr_static_response_cache($solrQuery->getSearcher());
    }

    $solrUrl = apachesolr_get_solr($env_id)->getUrl(); // e.g. http://localhost:8983/solr/drupal/

    if(isset($solrQuery)) {
      $solrParams = $solrQuery->getParams();
      $userSearch = drupal_encode_path($solrParams['q']);

      // build solr csv download link
      $export_title = t("Export search results");
      $downloadLink = $solrUrl . 'select?q=(' . $userSearch . ')' .
        '&rows=9999' .      // maximum number of search results to return
        '&qf=content&qf=label&qf=tags_inline&qf=taxonomy_names&qf=tos_content_extra&qf=tos_name&qf=ts_comments' .   // fields to search in
        '&fl=Typ:bundle_name,Titel:+label,Autoren:+tm_author,Jahr:+is_year,Beschreibung:+description' .             // fields to return with alias
        ',Anfangsdatum:+dm_field_anfangsdatum,Enddatum:+dm_field_enddatum,Link:+url,Schlagworte:+taxonomy_names' .
        '&wt=csv';          // return format
    }


    // Build a new header for the search results page that contains the CSV export link.

    if (isset($build['search_results']['search_title'])) {
      $title = $build['search_results']['search_title']['#markup'];
      $search_results_header = '<div class="search_results_header">' . $title .
        '<a id="exportcsv" href="' . $downloadLink . '" download="searchresults.csv">' .        // download file on click
        '<i title="' . $export_title . '" class="fa fa-file-text-o fa-2x" aria-hidden="true"></i>' .   // download icon (CSS)
        '</a></div>';
      $build['search_results']['search_title']['#markup'] = $search_results_header;
    }

    //check_url(url($path, $options))
    //dpm($build);
    //dpm($search_page);
  }
}