<?php
/**
 * @file
 * Allows trimmed comments to be displayed. New Comments will be displayed on top.
 */

/**
 * Implements Hook to attach JavaScript.
 *
 * @param $vars is called for every comment.
 */
function comments_shortener_preprocess_comment(&$vars) {
    drupal_add_js(drupal_get_path('module', 'comments_shortener') . "/js/comments_shortener.js", array('scope' => 'footer'));
    drupal_add_css(drupal_get_path('module', 'comments_shortener') . "/css/comments_shortener.css");
}


/**
 * Implements hook_query_TAG_alter().
 *
 * Alter comments query to order by DESC as well as the default ASC.
 */
function comments_shortener_query_comment_filter_alter(QueryAlterableInterface $query) {
    $orderby = &$query->getOrderBy();

    // Sorting for threaded comments.
    if (isset($orderby['torder'])) {
        // Sort by root parent first, then normal threaded.
        $query->addExpression("SUBSTRING_INDEX(c.thread, '.', 1)", 'rparent');
        $orderby = array('rparent' => 'DESC') + $orderby;
    }
    // Sorting for flat comments.
    else if (isset($orderby['c.cid'])) {
        $direction = 'DESC';

        $orderby['c.cid'] = $direction;
        $orderby = array('c.created' => $direction) + $orderby;
    }
}

function comments_shortener_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'comment_node_wissenskarte_form' && $form['#method'] == 'post') {
        array_push($form['#submit'], 'some_function');
    }
}

/**
 * Attaches the redirect to the submitted form.
 *
 * @param unknown_type $form
 * @param unknown_type $form_state
 * @return unknown
 */
function some_function($form, &$form_state) {
    // Redirect to the first page
    $form_state['redirect'][1]['query']['page'] = 0;
}

/**
 * Implements hook_help().
 * Display help link to README.txt in module overview (admin/modules).
 */
function comments_shortener_help($path, $arg) {
  switch ($path) {
    case 'admin/help#comments_shortener':
      $readme = file_get_contents(drupal_get_path('module', 'comments_shortener') . '/README.txt');
      return module_exists('markdown') ? filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $readme)) : '<pre>' . check_plain($readme) . '</pre>';
  }
}